services:
  db:
    image: mysql
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imbo_test
      MYSQL_USER: imbo_test
      MYSQL_PASSWORD: imbo_test
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  adminer:
    depends_on:
      - db
    image: adminer:latest
    ports:
      - "8888:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
