version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imbo_test
      MYSQL_USER: imbo_test
      MYSQL_PASSWORD: imbo_test
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      PMA_USER: imbo_test
      PMA_PASSWORD: imbo_test
